# Generated by Django 4.0.4 on 2022-05-06 00:40

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Vacuna',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=40)),
                ('informacion', models.TextField(max_length=700)),
            ],
            options={
                'verbose_name': 'vacuna',
                'verbose_name_plural': 'vacunas',
            },
        ),
        migrations.CreateModel(
            name='Vacunatorio',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=40)),
                ('ubicacion', models.CharField(max_length=40)),
            ],
        ),
        migrations.CreateModel(
            name='Usuario',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(help_text='Nombre de la persona', max_length=100)),
                ('apellido', models.CharField(help_text='Apellido de la persona', max_length=100)),
                ('fecha_nacimiento', models.DateField(help_text='Fecha de nacimiento de la persona')),
                ('dni', models.IntegerField(help_text='DNI de la persona', max_length=8)),
                ('residencia', models.TextField(help_text='Descripción de la tarea')),
                ('fecha_creacion', models.DateTimeField(auto_now_add=True)),
                ('historial_vacunas', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('id_vacunas_aplicadas', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='website.vacuna')),
            ],
        ),
    ]
