# Generated by Django 4.0.4 on 2022-05-17 02:12

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0002_user_delete_usuario'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='dni',
            field=models.IntegerField(help_text='DNI de la persona', null=True),
        ),
        migrations.AddField(
            model_name='user',
            name='fecha_creacion',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='user',
            name='fecha_nacimiento',
            field=models.DateField(help_text='Fecha de nacimiento de la persona', null=True),
        ),
        migrations.AddField(
            model_name='user',
            name='id_vacunas_aplicadas',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='website.vacuna'),
        ),
        migrations.AddField(
            model_name='user',
            name='residencia',
            field=models.TextField(help_text='Descripción de la tarea', null=True),
        ),
    ]
