# Generated by Django 4.0.4 on 2022-05-17 03:28

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0003_user_dni_user_fecha_creacion_user_fecha_nacimiento_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Usuario',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('username', models.CharField(max_length=100, unique=True, verbose_name='Nombre de usuario')),
                ('email', models.EmailField(max_length=254, unique=True, verbose_name='Correo electrónico')),
                ('nombre', models.CharField(max_length=254, verbose_name='Nombre')),
                ('apellido', models.CharField(max_length=254, verbose_name='apellido')),
                ('dni', models.IntegerField(help_text='DNI de la persona', unique=True)),
                ('fecha_nacimiento', models.DateField(help_text='Fecha de nacimiento de la persona')),
                ('residencia', models.TextField(help_text='Descripción de la tarea', null=True)),
                ('fecha_creacion', models.DateTimeField(auto_now_add=True)),
                ('usuario_activo', models.BooleanField(default=True)),
                ('usuario_administrador', models.BooleanField(default=False)),
                ('id_vacunas_aplicadas', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='website.vacuna')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.DeleteModel(
            name='User',
        ),
    ]
