# Generated by Django 4.0.4 on 2022-05-20 03:40

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0004_usuario_delete_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='usuario',
            name='vacunatorio_preferencia',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='website.vacunatorio'),
        ),
    ]
