# Generated by Django 4.0.4 on 2022-05-20 03:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0005_usuario_vacunatorio_preferencia'),
    ]

    operations = [
        migrations.AddField(
            model_name='usuario',
            name='historial_vacunacion',
            field=models.CharField(max_length=1000, null=True, verbose_name='Historial de vacunación'),
        ),
    ]
