# Generated by Django 4.0.4 on 2022-05-24 04:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0008_turno'),
    ]

    operations = [
        migrations.CreateModel(
            name='EstadosTurno',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('estado', models.CharField(max_length=30)),
            ],
        ),
        migrations.RenameField(
            model_name='usuario',
            old_name='id_vacunas_aplicadas',
            new_name='vacunas_aplicadas',
        ),
    ]
