# Generated by Django 4.0.4 on 2022-05-24 06:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0010_estadosturno_and_more.py'),
    ]

    operations = [
    ]
