# Generated by Django 4.0.4 on 2022-05-24 06:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0010_remove_usuario_vacunas_aplicadas_vacunadeusuario'),
        ('website', '0010_rename_username_turno_user'),
    ]

    operations = [
    ]
