# Generated by Django 4.0.4 on 2022-05-23 23:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0011_merge_20220524_0311.py'),
    ]

    operations = [
        migrations.RenameField(
            model_name='turno',
            old_name='username',
            new_name='user',
        ),
    ]
