# Generated by Django 4.0.4 on 2022-05-24 04:57

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0012_rename_username_turno_user.py'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='usuario',
            name='vacunas_aplicadas',
        ),
        migrations.CreateModel(
            name='VacunaDeUsuario',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('vacuna', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='website.vacuna')),
            ],
        ),
    ]
