# Generated by Django 4.0.4 on 2022-05-24 06:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0013_remove_usuario_vacunas_aplicadas_vacunadeusuario.py'),
    ]

    operations = [
        migrations.RenameField(
            model_name='turno',
            old_name='user',
            new_name='username',
        ),
    ]
