# Generated by Django 4.0.4 on 2022-05-24 06:28

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0014_rename_username_turno_user.py'),
    ]

    operations = [
        migrations.CreateModel(
            name='Historial_Vacunacion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha', models.DateField()),
                ('vacuna', models.CharField(max_length=20)),
            ],
        ),
        migrations.AlterField(
            model_name='usuario',
            name='historial_vacunacion',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='website.historial_vacunacion'),
        ),
    ]
