# Generated by Django 4.0.4 on 2022-05-24 06:57

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0015_historial_vacunacion_and_more.py'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='usuario',
            name='historial_vacunacion',
        ),
        migrations.AddField(
            model_name='historial_vacunacion',
            name='user',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
